import { requireOffUser, resolveDisplayName } from '../../_offFriends';

const ADMIN = new Set(['admin','owner']);
export async function onRequestGet(context:any){
 const auth=await requireOffUser(context); if(!auth.ok) return Response.json({error:auth.error},{status:auth.status});
 const u=new URL(context.request.url); const gameKey=u.searchParams.get('gameKey'); const limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||30))); const reqUserId=Number(u.searchParams.get('userId')||0);
 const userId = (reqUserId && ADMIN.has(String(auth.user.role||''))) ? reqUserId : Number(auth.user.id);
 const where=['1=1']; const args:any[]=[];
 if(gameKey){ where.push('m.game_key=?'); args.push(gameKey); }
 if(ADMIN.has(String(auth.user.role||''))){ if(reqUserId){ where.push('(m.host_user_id=? OR m.opponent_user_id=?)'); args.push(userId,userId);} }
 else { where.push('(m.host_user_id=? OR m.opponent_user_id=?)'); args.push(userId,userId); }
 const rows=await context.env.DB.prepare(`SELECT m.*, hu.name host_name, hu.email host_email, hu.nickname host_nickname, hop.display_name host_off_display_name, hu.avatar_url host_avatar_url, ou.name opp_name, ou.email opp_email, ou.nickname opp_nickname, oop.display_name opp_off_display_name, ou.avatar_url opp_avatar_url, wu.name winner_name, wu.email winner_email, wu.nickname winner_nickname, wop.display_name winner_off_display_name, lu.name loser_name, lu.email loser_email, lu.nickname loser_nickname, lop.display_name loser_off_display_name FROM off_match_history m LEFT JOIN users hu ON hu.id=m.host_user_id LEFT JOIN off_profiles hop ON hop.user_id=hu.id LEFT JOIN users ou ON ou.id=m.opponent_user_id LEFT JOIN off_profiles oop ON oop.user_id=ou.id LEFT JOIN users wu ON wu.id=m.winner_user_id LEFT JOIN off_profiles wop ON wop.user_id=wu.id LEFT JOIN users lu ON lu.id=m.loser_user_id LEFT JOIN off_profiles lop ON lop.user_id=lu.id WHERE ${where.join(' AND ')} ORDER BY m.id DESC LIMIT ?`).bind(...args,limit).all<any>();
 const matches=(rows.results||[]).map((r:any)=>({id:r.id,gameKey:r.game_key,gameLabel:r.game_label,lobbyId:r.lobby_id,status:r.status,host:{id:r.host_user_id,displayName:resolveDisplayName({name:r.host_name,email:r.host_email,nickname:r.host_nickname,off_display_name:r.host_off_display_name}),avatarUrl:r.host_avatar_url||null},opponent:r.opponent_user_id?{id:r.opponent_user_id,displayName:resolveDisplayName({name:r.opp_name,email:r.opp_email,nickname:r.opp_nickname,off_display_name:r.opp_off_display_name}),avatarUrl:r.opp_avatar_url||null}:null,winner:r.winner_user_id?{id:r.winner_user_id,displayName:resolveDisplayName({name:r.winner_name,email:r.winner_email,nickname:r.winner_nickname,off_display_name:r.winner_off_display_name})}:null,loser:r.loser_user_id?{id:r.loser_user_id,displayName:resolveDisplayName({name:r.loser_name,email:r.loser_email,nickname:r.loser_nickname,off_display_name:r.loser_off_display_name})}:null,result:r.result_json?JSON.parse(r.result_json):null,gameSettings:r.game_settings_json?JSON.parse(r.game_settings_json):null,startedAt:r.started_at,completedAt:r.completed_at,durationSeconds:r.duration_seconds,createdAt:r.created_at}));
 return Response.json({ok:true,matches});
}
