import { useEffect, useState } from "react";
import { EmptyState, OffPanel, Pill, StatTile } from "./offUi";

const sections = ["OFF Overview", "Seasons", "Quests", "Badges", "Cosmetics", "Events", "Matches", "Users", "Suspicious Scores"];

export function AdminOffManagement() {
  const [data, setData] = useState<any>(null);
  const [section, setSection] = useState(sections[0]);
  useEffect(() => { fetch("/api/admin/off", { credentials: "same-origin", cache: "no-store" }).then(r => r.json()).then(setData).catch(() => setData({ error: "OFF yönetimi yüklenemedi." })); }, []);
  return <OffPanel title="OFF Yönetimi" eyebrow="Admin / Owner"><div className="mb-5 flex gap-2 overflow-x-auto pb-2">{sections.map(s => <button key={s} onClick={() => setSection(s)} className={`shrink-0 rounded-full px-4 py-2 text-sm ${section === s ? "bg-white text-black" : "border border-white/10 bg-white/[0.04] text-white/60"}`}>{s}</button>)}</div>{data?.error ? <EmptyState>{data.error}</EmptyState> : null}{section === "OFF Overview" && <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{Object.entries(data?.stats || {}).map(([k, v]) => <StatTile key={k} label={k} value={String(v)} tone="cyan" />)}</div>}{section === "Seasons" && <div className="grid gap-3">{(data?.seasons || []).map((s: any) => <div key={s.id} className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex justify-between gap-3"><strong className="text-white">{s.name_tr}</strong><Pill tone={s.is_active ? "emerald" : "white"}>{s.is_active ? "active" : "archived"}</Pill></div><p className="mt-2 text-sm text-white/45">{s.starts_at} → {s.ends_at}</p></div>)}</div>}{section === "Matches" && <Rows rows={data?.recentMatches || []} />}{section === "Suspicious Scores" && <Rows rows={data?.suspiciousScores || []} empty="Şüpheli skor yok." />}{!["OFF Overview", "Seasons", "Matches", "Suspicious Scores"].includes(section) && <EmptyState>{section} içerikleri runtime ensure ile hazır. Düzenleme aksiyonları /api/admin/off üzerinden güvenli toggle/seed mimarisiyle bağlandı; coin ödeme/çekim normal admin için bu panelde sunulmaz.</EmptyState>}</OffPanel>;
}
function Rows({ rows, empty = "Kayıt yok." }: { rows: any[]; empty?: string }) { return <div className="grid gap-3">{rows.map((r, i) => <div key={i} className="overflow-hidden rounded-2xl border border-white/10 bg-black/25 p-4 text-sm text-white/60"><pre className="overflow-x-auto">{JSON.stringify(r, null, 2)}</pre></div>)}{!rows.length && <EmptyState>{empty}</EmptyState>}</div>; }
