import { useEffect, useState } from "react";
import { EmptyState, OffPanel, Pill, StatTile } from "./offUi";

export function OffProfile() {
  const [data, setData] = useState<any>(null);
  useEffect(() => { let on = true; fetch("/api/off-profile", { credentials: "same-origin", cache: "no-store" }).then(r => r.json()).then(d => { if (on) setData(d); }); return () => { on = false; }; }, []);
  const user = data?.user || {}; const profile = data?.profile || {}; const level = data?.level || {}; const wallet = data?.wallet || {};
  return <div className="space-y-5"><OffPanel title="OFF Profil" eyebrow="Public profile" action={level.level >= 10 ? <Pill tone="cyan">✓ Level 10+ verified</Pill> : <Pill tone="white">Level 10’da verified</Pill>}>
    <div className="flex flex-col gap-5 lg:flex-row lg:items-center"><div className="relative h-24 w-24 overflow-hidden rounded-[2rem] border border-white/15 bg-white/10">{user.avatar_url ? <img src={user.avatar_url} alt={user.name} className="h-full w-full object-cover" /> : <div className="flex h-full w-full items-center justify-center text-3xl font-bold">{String(user.name || "O")[0]}</div>}</div><div className="min-w-0 flex-1"><h3 className="text-3xl font-semibold">{profile.display_name || user.name || "OFF Player"}</h3><div className="mt-3 flex flex-wrap gap-2"><Pill>{user.role || "off"}</Pill><Pill tone="cyan">Lv. {level.level || 1}</Pill><Pill tone="amber">{wallet.balance || 0} TC</Pill></div></div></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatTile label="Lifetime earned" value={wallet.lifetime_earned || 0} tone="amber"/><StatTile label="Toplam maç" value={profile.total_matches || 0}/><StatTile label="Galibiyet / Mağlubiyet" value={`${profile.wins || 0}/${profile.losses || 0}`} tone="cyan"/><StatTile label="En çok oynanan" value={profile.favorite_game || "-"} tone="purple"/></div>
    <div className="mt-5 h-3 overflow-hidden rounded-full bg-black/40 ring-1 ring-white/10"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-purple-400" style={{ width: `${Math.max(0, Math.min(100, ((level.expIntoLevel || 0) / Math.max(1, (level.nextLevelExp || 1) - (level.currentLevelExp || 0))) * 100))}%` }} /></div>
  </OffPanel>
  <OffPanel title="Son 10 maç"><div className="grid gap-3">{(data?.recentMatches || []).length ? data.recentMatches.map((m: any) => <div key={m.public_id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-black/25 p-4 text-sm"><span className="font-semibold text-white">{m.game_key}</span><Pill tone={m.result === "win" ? "emerald" : m.result === "loss" ? "amber" : "white"}>{m.result}</Pill><span className="text-white/45">{m.exp_earned || 0} XP · {m.points_earned || 0} TC</span></div>) : <EmptyState>Henüz maç kaydı yok.</EmptyState>}</div></OffPanel>
  <OffPanel title="Rozetler ve kullanılan kozmetikler"><div className="flex flex-wrap gap-2">{(data?.badges || []).map((b: any) => <Pill key={b.slug} tone={b.rarity === "legendary" ? "amber" : "purple"}>{b.icon} {b.title_tr}</Pill>)}{!(data?.badges || []).length && <EmptyState>Rozetler maç/görev tamamladıkça burada açılır.</EmptyState>}</div><div className="mt-4 grid gap-3 sm:grid-cols-3"><StatTile label="Frame" value={profile.equipped_frame_slug || "-"}/><StatTile label="Avatar glow" value={profile.equipped_avatar_glow_slug || "-"}/><StatTile label="Name tag" value={profile.equipped_name_tag_slug || "-"}/></div></OffPanel></div>;
}
