import { useEffect, useMemo, useState } from "react";
import { EmptyState, OffPanel, Pill } from "./offUi";

export function OffQuests() {
  const [data, setData] = useState<any>({ quests: [], progress: [] }); const [message, setMessage] = useState("");
  const load = () => fetch("/api/off-quests", { credentials: "same-origin", cache: "no-store" }).then(r => r.json()).then(setData).catch(() => setMessage("Görevler yüklenemedi."));
  useEffect(() => { load(); }, []);
  const progress = useMemo(() => new Map((data.progress || []).map((p: any) => [`${p.quest_slug}:${p.period_key}`, p])), [data]);
  const claim = async (q: any) => { setMessage(""); const r = await fetch("/api/off-quests", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questSlug: q.slug, periodKey: q.period_key }) }); const d = await r.json().catch(() => null); setMessage(r.ok ? "Görev ödülü claim edildi." : d?.error || "Claim başarısız."); if (r.ok) { window.dispatchEvent(new Event("ekatech-techcoin-refresh")); load(); } };
  return <OffPanel title="OFF Görevleri" eyebrow="Daily / Weekly / Event" action={message ? <Pill tone="cyan">{message}</Pill> : null}><div className="grid gap-4 md:grid-cols-2">{(data.quests || []).map((q: any) => { const p: any = progress.get(`${q.slug}:${q.period_key}`) || {}; const current = Number(p.current_count || 0), target = Number(p.target_count || q.target_count || 1); const done = Boolean(p.completed_at) || current >= target; return <div key={q.slug} className="rounded-2xl border border-white/10 bg-black/25 p-4"><div className="flex items-start justify-between gap-3"><div><Pill tone={q.type === "weekly" ? "amber" : "purple"}>{q.type}</Pill><h3 className="mt-3 text-lg font-semibold text-white">{q.title_tr}</h3><p className="mt-2 text-sm leading-6 text-white/45">{q.description_tr}</p></div><Pill tone={done ? "emerald" : "white"}>{current}/{target}</Pill></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-purple-400 to-cyan-300" style={{ width: `${Math.min(100, (current / Math.max(1, target)) * 100)}%` }} /></div><div className="mt-4 flex items-center justify-between gap-3 text-sm text-white/55"><span>+{q.reward_exp} XP · +{q.reward_points} TC</span><button disabled={!done || Boolean(p.claimed_at)} onClick={() => claim(q)} className="rounded-full bg-white px-4 py-2 text-xs font-semibold text-black disabled:opacity-40">{p.claimed_at ? "Claim edildi" : "Claim"}</button></div></div>; })}{!(data.quests || []).length && <EmptyState>Aktif görev yok.</EmptyState>}</div></OffPanel>;
}
